import { Request, Response, NextFunction } from "express";
import { customer } from "../db";
import { transformAttributesToSchema } from "../utils/Helpers";
const SAFE_FIELDS = ["name", "email", "createdAt"];
export const getCustomerModel = async (
  req: Request,
  res: Response,
  next: NextFunction
) => {
  try {
    const schema = customer.getAttributes();
    const parsedSchema = transformAttributesToSchema<customerSchema>(schema);
    console.log(parsedSchema);
    res.status(200).json(parsedSchema);
  } catch (error) {
    console.log(error);
  }
};


type customerSchema = {
  [key: string]: {
    type: string; // Type key, e.g., 'STRING', 'INTEGER', etc.
    primaryKey?: boolean;
    autoIncrement?: boolean;
    allowNull?: boolean;
    defaultValue?: any;
    fieldName?: string;
    _modelAttribute?: boolean;
    field?: string;
    _autoGenerated?: boolean;
    references?: { model: string; key: string };
  };
};
