import { Request, Response, NextFunction } from "express";
import { orderitems } from "../db";
import { transformAttributesToSchema } from "../utils/Helpers";

export const getOrderItemModel = async (
  req: Request,
  res: Response,
  next: NextFunction
) => {
  try {
    const schema = orderitems.getAttributes();
    const parsedSchema = transformAttributesToSchema<OrderItemSchema>(schema);
    res.status(200).json(parsedSchema);
  } catch (error) {
    console.log(error);
  }
};

 type OrderItemSchema = {
  [key: string]: {
    type: string; // Type key, e.g., 'STRING', 'INTEGER', etc.
    primaryKey?: boolean;
    autoIncrement?: boolean;
    allowNull?: boolean;
    defaultValue?: any;
    fieldName?: string;
    _modelAttribute?: boolean;
    field?: string;
         _autoGenerated?: boolean;
         references?: { model: string; key: string };
  };
};

